const JIRAMA='https://www.jirama.mg/portal';
const headers={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const reply=(body,status=200)=>new Response(JSON.stringify(body),{status,headers});
const clean=s=>(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#039;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
function infoFrom(html){
 const name=(html.match(/Client\s*:\s*([^<\r\n]+)/i)||[])[1]||(html.match(/(?:Nom|Titulaire)\s*:\s*<[^>]*>([^<]+)/i)||[])[1];
 const dates=clean(html).match(/(?:entre|du)\s*(\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4})\s*(?:et|au|à|-)\s*(\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4})/i)||clean(html).match(/(\d{1,2}\/\d{1,2}\/\d{2,4})\s*(?:au|à|-)\s*(\d{1,2}\/\d{1,2}\/\d{2,4})/i);
 let startDate=dates?.[1]||'',endDate=dates?.[2]||'',inPeriod=false;
 const parse=x=>{const [d,m,y]=x.split(/[\/.-]/).map(Number);return new Date(y<100?2000+y:y,m-1,d)};
 if(startDate&&endDate){const now=new Date(),start=parse(startDate),end=parse(endDate);end.setHours(23,59,59,999);inPeriod=now>=start&&now<=end}
 return{clientName:clean(name)||'CLIENT JIRAMA',startDate,endDate,periodDates:startDate&&endDate?`${startDate} - ${endDate}`:'NON DISPONIBLE',inPeriod};
}
function fieldsFrom(html){const out={};for(const tag of html.match(/<input\b[^>]*>/gi)||[]){const n=(tag.match(/\bname=["']([^"']+)["']/i)||[])[1];if(!n)continue;out[n]=(tag.match(/\bvalue=["']([^"']*)["']/i)||[])[1]||''}return out}
function cookieFrom(res){const raw=res.headers.get('set-cookie')||'';return raw.split(/,(?=[^;,]+=)/).map(x=>x.split(';')[0]).join('; ')}
async function identify(ref,num){const body=new URLSearchParams({reference:ref,numero:num});const res=await fetch(`${JIRAMA}/espace/client/info-client`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','x-requested-with':'XMLHttpRequest','referer':`${JIRAMA}/espace/autoreleve`},body,redirect:'follow'});const html=await res.text();if(!res.ok)throw Error(`JIRAMA indisponible (${res.status})`);const info=infoFrom(html);const noClient=!info.startDate&&!Object.keys(fieldsFrom(html)).length&&info.clientName==='CLIENT JIRAMA';if(noClient)throw Error('Référence ou numéro client non reconnu par JIRAMA.');return{html,info,cookie:cookieFrom(res)}}
export async function onRequestPost({request}){try{const data=await request.json(),ref=String(data.ref||''),num=String(data.num||'');if(!ref||!num)return reply({success:false,message:'Référence et numéro client requis.'},400);const first=await identify(ref,num);if(data.action==='verify')return reply({success:true,...first.info});const reading=String(data.reading||'');if(!/^\d+$/.test(reading))return reply({success:false,message:'Index numérique invalide.'},400);const fields=fieldsFrom(first.html);let indexKey=Object.keys(fields).find(k=>/(index|releve|lecture)/i.test(k)&&!/(ancien|old)/i.test(k));if(!indexKey)indexKey='index';fields[indexKey]=reading;if(!Object.keys(fields).some(k=>/reference/i.test(k)))fields.reference=ref;if(!Object.keys(fields).some(k=>/numero/i.test(k)))fields.numero=num;const res=await fetch(`${JIRAMA}/espace/index/update`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','x-requested-with':'XMLHttpRequest','referer':`${JIRAMA}/espace/autoreleve`,...(first.cookie?{cookie:first.cookie}:{})},body:new URLSearchParams(fields)});const text=await res.text();let payload={};try{payload=JSON.parse(text)}catch{}const message=payload?.data?.message||payload?.message||clean(text);const ok=res.ok&&(payload?.data?.success===true||payload?.success===true||/succès|enregistr|pris en compte|merci/i.test(message));if(!ok)return reply({success:false,...first.info,message:message&&message.length<240?message:'Relevé refusé par JIRAMA. Vérifiez la période et la valeur saisie.'},422);return reply({success:true,...first.info,message:message||'Relevé transmis avec succès.'});}catch(e){return reply({success:false,message:e.message||'Erreur de communication avec JIRAMA.'},500)}}
export async function onRequestOptions(){return new Response(null,{status:204,headers:{allow:'POST, OPTIONS'}})}
